function [ Rtilt ] = tiltMatrix(thetaTilt)

Rtilt = [ cos(thetaTilt)  -sin(thetaTilt)    0 ; ...
          sin(thetaTilt)  cos(thetaTilt)     0 ; ... 
                0                 0          1];
end